#!/bin/bash
# Add the call to our script at the beginning and clean up
printf "source /etc/dhcp-update\n" > udhcpc.user
if [[ -f /etc/udhcp.old]]; then 
  cat udhcpc.old >> udhcpc.user
  rm /etc/udhcpc.old
fi
#Calling script must use bash
sed -i '1c#!/bin/bash' /lib/netifd/dhcp.script 
exit 0
